name = "medium"
main = "src/index.ts"
compatibility_date = "2024-12-25"

# compatibility_flags = [ "nodejs_compat" ]

 [vars]
 DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjRlYTI1N2YtNTI5Yy00ODYzLTk0MTgtMTU2YzIwYzM5ZTMyIiwidGVuYW50X2lkIjoiMDk4MjEzYjAyNmQ4ODIwYTg1MzU4YmJlMWVmZTlmZjJmOWIzNmM3N2IyNzgzZTJmNDYwZjE3NzVjOWRmZjIyOCIsImludGVybmFsX3NlY3JldCI6ImM0ODFhMzg2LWNlZTUtNGNkZC04YjUxLWZhYTEyYTBiYmU5ZiJ9.EiV9b4BgY8gQyUMZasuJAwZWIRBfy_QvbEvHioityek"
JWT_SECRET="pintusecret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1